spring.application.name=wildfire
spring.datasource.url=jdbc:mysql://localhost:3306/dbtemp
spring.datasource.username=root
spring.datasource.password=SqlServer1!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.env=dev

# application.properties
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.boot.autoconfigure=INFO


jwt.secret=dB4Ij0DQJF3tx1p8t+qsg/rhPQYIAOsJiyeYjzimh9Hsfti4Ydb2gbbQVnvWcB2+qEsEZ0jpG25JbCKaj1EikA==
jwt.expiration=3600000

# Enable multipart uploads
spring.servlet.multipart.enabled=true

# Max file size
spring.servlet.multipart.max-file-size=5MB

# Max request size
spring.servlet.multipart.max-request-size=5MB